
export const LOAD_CANDIDATES_SUCCESS = 'LOAD_CANDIDATES_SUCCESS';
export const LOAD_CANDIDATE_SUCCESS = 'LOAD_CANDIDATE_SUCCESS';

export const LOAD_CANDIDATE_UPDATE_FIELD = 'LOAD_CANDIDATE_UPDATE_FIELD';