

export const CONTROLS_ADMIN_SUCCESS = 'CONTROLS_ADMIN_SUCCESS'
export const CONTROLS_PRODUCTION_SUCCESS = 'CONTROLS_PRODUCTION_SUCCESS'
export const CONTROLS_CORONATION_SUCCESS = 'CONTROLS_CORONATION_SUCCESS'
export const CONTROLS_TALENT_SUCCESS = 'CONTROLS_TALENT_SUCCESS'
export const CONTROLS_FINAL_SUCCESS = 'CONTROLS_FINAL_SUCCESS'

