export const FINAL_ROUND_STATUS = 'FINAL_ROUND_STATUS'
export const FINAL_ROUND_GETSCORES_SUCCESS = 'FINAL_ROUND_GETSCORES_SUCCESS'
export const FINAL_ROUND_INTERVIEW_SUCCESS = 'FINAL_ROUND_INTERVIEW_SUCCESS'
export const FINAL_ROUND_POISE_SUCCESS = 'FINAL_ROUND_POISE_SUCCESS'