/**
 * Created by albertoclarit on 9/18/16.
 */

export const LOAD_FINALROUND_CANDIDATES_SUCCESS = 'LOAD_FINALROUND_CANDIDATES_SUCCESS';

export const FINALROUND_NEXT_CANDIDATE = 'FINALROUND_NEXT_CANDIDATE';
export const FINALROUND_PREVIOUS_CANDIDATE = 'FINALROUND_PREVIOUS_CANDIDATE';


export const LOAD_FINALROUND_SCORE_SUCCESS = 'LOAD_FINALROUND_SCORE_SUCCESS';

export const LOAD_ALL_FINALROUND_SCORES_SUCCESS = 'LOAD_ALL_FINALROUND_SCORES_SUCCESS'